apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - image: arunramakani/inventory
        name: inventory
        env:
        - name: DATABASE_HOST
          value: mysql
        ports:
        - containerPort: 8080
          protocol: TCP
          name: inventory
        