kind: Service
apiVersion: v1
metadata:
  name: inventory
spec:
  selector:
    run: inventory
  ports:
    - name: inventoryport
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort