kind: Service
apiVersion: v1
metadata:
  name: purchase
spec:
  selector:
    run: purchase
  ports:
    - name: inventoryport
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort